### ISSUE TITLE
groupadd: GID '0' already exists

### ISSUE THREAD

**Issue by garblixa** [linuxmuster/linbo-build-docker#1]
When running ./setup_env.sh I got the error:
```
groupadd: GID '0' already exists
```
You can fix this, when you call groupadd with the parameter "-f" in Dockerfile. After fixing this, another error came up:
```
useradd: UID 0 is not unique
```
You can fix this, when you call useradd with the parameter "-o" in Dockerfile. Here is the diff:
```
# diff Dockerfile Dockerfile.DIST 
20,21c20,21
< RUN groupadd -f -g ${MY_GID} ${MY_USER}
< RUN useradd -o -s /bin/bash -c 'linbo build user' -d /home/${MY_USER} -M -u ${MY_UID} -g ${MY_USER} -G sudo ${MY_USER}
---
> RUN groupadd -g ${MY_GID} ${MY_USER}
> RUN useradd -s /bin/bash -c 'linbo build user' -d /home/${MY_USER} -M -u ${MY_UID} -g ${MY_USER} -G sudo ${MY_USER}
```

**Comment by HappyBasher** [comment]
The scripts should be invoked as an unprivileged user, not as root. User has to be in group docker.
